### ISSUE TITLE
This package needs a license

### ISSUE THREAD

**Issue by saltmueller** [yosuke-furukawa/json5#7]
There is no license defined and some of the source files contain headers probably copied from other packages. 
i.e. https://github.com/yosuke-furukawa/json5/blob/master/encoding/json5/encode_test.go

Preferably a BSD style license.

**Comment by cpedlar-syn** [comment]
Adding another request here to try to get a license added.  I'd like to make use of this package but cannot unless a license is added.

**Comment by tcd** [comment]
@yosuke-furukawa ping

**Comment by yosuke-furukawa** [comment]
done https://github.com/yosuke-furukawa/json5/blob/master/LICENSE.md
